/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JProgressBar;
/**
 *
 * @author kkjjk
 */
public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        none = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnSearch = new javax.swing.JButton();
        lblStartVal = new javax.swing.JLabel();
        lblEndVal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLow = new javax.swing.JLabel();
        lblHigh = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblSound = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        lblVal = new javax.swing.JLabel();
        txtStateInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        lblTitle.setText("Progress Bar 예제");

        lblProgress.setText("진행");

        jProgressBar1.setStringPainted(true);

        btnSearch.setText("검색시작");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblStartVal.setText("0");

        lblEndVal.setText("100");

        javax.swing.GroupLayout noneLayout = new javax.swing.GroupLayout(none);
        none.setLayout(noneLayout);
        noneLayout.setHorizontalGroup(
            noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noneLayout.createSequentialGroup()
                .addGroup(noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noneLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnSearch))
                    .addGroup(noneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProgress)
                        .addGap(18, 18, 18)
                        .addGroup(noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(noneLayout.createSequentialGroup()
                                .addComponent(lblStartVal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEndVal))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(124, 124, 124))
        );
        noneLayout.setVerticalGroup(
            noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noneLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgress)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noneLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(41, 41, 41))
                    .addGroup(noneLayout.createSequentialGroup()
                        .addGroup(noneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartVal)
                            .addComponent(lblEndVal))
                        .addGap(93, 93, 93))))
        );

        jTabbedPane1.addTab("progress", none);

        lblLow.setText("낮음");

        lblHigh.setText("높음");

        lblTitle1.setText("Slider 예제");

        lblSound.setText("Sound");

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        lblVal.setText("50");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblSound)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLow)
                        .addGap(107, 107, 107)
                        .addComponent(lblVal)
                        .addGap(107, 107, 107)
                        .addComponent(lblHigh))
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle1)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSound)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLow)
                    .addComponent(lblHigh)
                    .addComponent(lblVal))
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("slide", jPanel2);

        txtStateInfo.setText("상태 정보 출력");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStateInfo)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int iTabindex = 0;          //jTabbedPane1 index 저장 변수
        String strTabTitle = null;  //jTabbedPane1 Title 저장 변수
        
        iTabindex = jTabbedPane1.getSelectedIndex();
        strTabTitle = jTabbedPane1.getTitleAt(iTabindex);
        txtStateInfo.setText(strTabTitle + " 정보를 볼 수 있습니다.");
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Thread objThread = new PBarThread(jProgressBar1);
        objThread.start();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        String strData = null;
        int iValue = 0;
        
        iValue = jSlider1.getValue();
        strData = Integer.toString(iValue);
        lblVal.setText(strData);
    }//GEN-LAST:event_jSlider1StateChanged

    public class PBarThread extends Thread {
        final static int DELAY = 500;
        JProgressBar objProgressBar;

        public PBarThread(JProgressBar objPB) {
         objProgressBar = objPB;
         objProgressBar.setStringPainted(true);
        }
        
        public void run(){
            int minValue = objProgressBar.getMinimum();     //Progressbar Minimum값,
            int maxValue = objProgressBar.getMaximum();     //Progressbar Maximum값,
            
            for(int idx = minValue; idx < maxValue; idx++){
                try{
                    int iValue = objProgressBar.getValue(); 
                    objProgressBar.setValue(iValue+1);      //Progressbar 값에 1추가
                    Thread.sleep(DELAY);                    //DELAY 500밀리초
                }catch(InterruptedException ignoredException){
                }
            }       //반복문 종료
        }           //run 함수 종료
    }               //PBarThread 클래스 종료
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEndVal;
    private javax.swing.JLabel lblHigh;
    private javax.swing.JLabel lblLow;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblSound;
    private javax.swing.JLabel lblStartVal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblVal;
    private javax.swing.JPanel none;
    private javax.swing.JTextField txtStateInfo;
    // End of variables declaration//GEN-END:variables
}
